### ISSUE TITLE
Provide installation docs as requried by AGPLv3 License

### ISSUE THREAD

**Issue by febrezo** [zotero/dataserver#107]
As other users in the past, I have been trying. Using a third party platform hosted outside our jurisdiction even if it is for metadata only is not an option so I have tried to understand the different pieces which lead to a fully-working server. 

This is a bit discouraging for me taking into account that this is required by the AGPLv3 License, a License which full text is reproduced in this project [here](https://github.com/zotero/dataserver/blob/4d09a0d4d2902eec93b60ca963d9a5e3f2f8e1d8/COPYING#L314) since June 2010.

```
  "Installation Information" for a User Product means any methods,
procedures, authorization keys, or other information required to install
and execute modified versions of a covered work in that User Product from
a modified version of its Corresponding Source.  The information must
suffice to ensure that the continued functioning of the modified object
code is in no case prevented or interfered with solely because
modification has been made.
```

At the moment, we do have to make a reverse engineering process to understand components, variables and requirements, which is something that I'm sure that is documented for keeping alive Zotero live instances. I want to highlight that I really appreciate your work and that AGPL is THE LICENSE to match the project goals since it enforces anyone deploying or using a derivative work from Zotero server-side code to share the improvements with anyone getting connected to the new instance. This is the spirit of the text. But, unfortunately, we cannot say that this code is, at the moment of writing, AGPL code if the installation information is missing and cannot be effectively reproduced by others.

Thus, I want to offer my help, and probably that of many other free software contributors to build the docs for an easy-to-deploy server-side instance so as to match the requirements of the license. Integration with other technologies such as Docker or Docker-Compose may help for a quick local and private deployment, boost information sharing and, ultimately, make Zotero browser plugins and applications a de-facto standard for bibliography management.

**Comment by dstillman** [comment]
For the general topic, see my two comments at https://github.com/zotero/dataserver/issues/105#issuecomment-701854388. This isn't a documentation issue.

> But, unfortunately, we cannot say that this code is, at the moment of writing, AGPL code if the installation information is missing and cannot be effectively reproduced by others.

This just isn't true. We wrote the code and make it available under the AGPL, but we have no obligation to provide installation information ourselves. (And as explained in the linked issue, any self-hosting documentation would be completely different from what we do internally.)

> [The AGPL] enforces anyone deploying or using a derivative work from Zotero server-side code to share the improvements with anyone getting connected to the new instance.

No, that's not correct. The AGPL [permits anyone to use the software internally](https://www.gnu.org/licenses/gpl-faq.html#InternalDistribution) to their organization without triggering distribution requirements, and a number of organizations do so.
