### ISSUE TITLE
PHP8 support?

### ISSUE THREAD

**Issue by RaitoBezarius** [zotero/dataserver#128]
Hi there, I am interested into running this, but I see it is locked to PHP 7.0 due to:

```
  Problem 1
    - doctrine/cache is locked to version v1.6.2 and an update of this package was not requested.
    - doctrine/cache v1.6.2 requires php ~5.5|~7.0 -> your php version (8.1.9) does not satisfy that requirement.
  Problem 2
    - elasticsearch/elasticsearch is locked to version v6.5.0 and an update of this package was not requested.
    - elasticsearch/elasticsearch v6.5.0 requires php ^7.0 -> your php version (8.1.9) does not satisfy that requirement.
 ``` 

PHP7.0 is EOL since 2018 AFAIK, and PHP7.4 is going to die soon (in some months AFAIK).
Would you be interested into a PR to update those dependencies?

Also, I noticed there is no release to this repository, do you think, it would be possible to mark at least one release?

**Comment by dstillman** [comment]
Now compatible with 8.1
