### ISSUE TITLE
Public group returning 403/405 for HEAD request

### ISSUE THREAD

**Issue by ABouchard55** [zotero/dataserver#139]
The problem doesn't seem to come from the code, so I'm guessing it's a server configuration thing.

I have clients that use RSS feed links that come from api.zotero.org, but most RSS reading library use a HEAD request to validate the Last-Modified header, and api.zotero.org returns a 405 HTTP Status, saying it only accepts GET and POST requests.

**Comment by dstillman** [comment]
We'd need a specific request that's failing. You can x out the key. HEAD requests against the API should work, and do for me.

**Comment by ABouchard55** [comment]
The example I have for now is this:
https://api.zotero.org/groups/2531888/collections/8UYSYFY2/items/top?direction=desc&format=atom&sort=dateAdded&key=

Weirdly, with or without the key, it works with GET.

For HEAD, with the key, I get 405 Method not allowed, and without, I get a 403 Forbidden (which, I guess, should probably be returned by GET also if there's no key).

**Comment by ABouchard55** [comment]
@dstillman  Ahh, after you transferred the issue to zotero/dataserver, I did find a condition if the code that end the request for HEAD method in the Groups_controller.

**Comment by dstillman** [comment]
> Weirdly, with or without the key, it works with GET.

It's a public group.

But I am seeing the 403 for a HEAD without a key, which is wrong. We'll investigate.

> I did find a condition if the code that end the request for HEAD method in the Groups_controller.

It stops the request on a HEAD because a HEAD doesn't return data, only headers. That doesn't trigger a 4xx.
