### ISSUE TITLE
Support remote citation styles

### ISSUE THREAD

**Issue by dstillman** [zotero/dataserver#24]
Should be possible with https://github.com/zotero/citeproc-node/issues/18

Not sure if there are any sorts of limits/restrictions we need. @fcheslack, will used styles fall out of the cache eventually?

**Comment by fcheslack** [comment]
They would have eventually. Now they should do so correctly. 

I was also unsure about possible restrictions.

**Comment by rmzelle** [comment]
Any ETA on this?

**Comment by dstillman** [comment]
Available now

**Comment by rmzelle** [comment]
Is this really live yet? https://api.zotero.org/users/475425/items/X42A7DEE?format=bib&style=https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl and https://api.zotero.org/users/475425/items/X42A7DEE?format=bib&style=https%3A%2F%2Fraw.githubusercontent.com%2Fcitation-style-language%2Fstyles%2Fmaster%2Fapa.csl (encoded via http://meyerweb.com/eric/tools/dencoder/) still both give "Style not found" for me.

**Comment by dstillman** [comment]
Sorry, still had an out-of-date citeproc-node version running. Try again now.

**Comment by rmzelle** [comment]
Seems to work great, thanks!
