### ISSUE TITLE
Request headers are case sensitive

### ISSUE THREAD

**Issue by will-hart** [zotero/dataserver#27]
The API server expects headers matching a certain case - i.e. it will accept `Authorization` but not `authorization`. The [HTTP standards](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html) say headers are case-insensitive and as a result some HTTP request libraries (such as the built-in JavaScript [`fetch()`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalFetch/fetch#Syntax)) are incompatible with the Zotero API. 

This occurs because `fetch` appears to convert all custom request headers to lower case which means any authorized URL will always return a `403`. I've confirmed this in the current version of Atom Electron, `Chrome/47.0.2526.73 Electron/0.36.2` and the latest version of [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop).

I'm not particularly familiar with the `dataserver` code base, but it looks like looping over the `apache_request_headers()` and converting to lower case in the [`apiController`](https://github.com/zotero/dataserver/blob/master/controllers/ApiController.php#L196) could fix the issue? Happy to submit a pull request if this fix is suitable.

**Comment by dstillman** [comment]
Fixed — thanks. As you hopefully discovered in the intervening 15 months, this applied only to the `Authorization` header. All other headers worked as lowercase, including `Zotero-API-Key`, which (along with the `key` query parameter) could be used in place of `Authorization`.
