### ISSUE TITLE
Flexible storage backend

### ISSUE THREAD

**Issue by afif-elghraoui** [zotero/dataserver#29]
I'm looking into packaging this, but it seems that this requires the use of Amazon S3 storage. I was considering using a more flexible interface like [Flysystem](http://flysystem.thephpleague.com/), which would allow for one API, but allowing use of different storage backend. Would this be something that you might consider integrating?

**Comment by dstillman** [comment]
I don't think we'd go this route — we have additional AWS dependencies (e.g., SQS/SNS for push-based syncing in the upcoming 5.0), and if anything we'll be adding others, so storage will just be one requirement. I think it makes more sense for people who want to run their own servers to use various software that provides AWS-compatible APIs — of which S3 is by far the easiest and most common.

Re: packaging, see also [my recent post](https://groups.google.com/d/msg/zotero-dev/efFuMEqLarY/dx05dzmdEwAJ) on zotero-dev, which talks about our own plans for providing more official support for third-party installations after 5.0 is out.

**Comment by afif-elghraoui** [comment]
Sounds good. Thanks for the information.
