### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by pierwill** [zotero/dataserver#75]
This repo should be documented with at least a simple readme. If I can wrap my head around it, I'll get one started.

**Comment by dstillman** [comment]
Thanks, but we don't currently provide any support or documentation for the dataserver, and won't accept any documentation here — it's currently just not designed for custom installations (though some people have managed to get a version from several years ago running).

After we drop 4.0 syncing support in a few months, we'll be able to streamline the code and make installation, testing, and maintenance somewhat simpler, and we plan to offer a Docker-based version at that time (though it will likely still require various AWS services). Once that's available, we'll provide documentation.

**Comment by pierwill** [comment]
Thanks for the info!

**Comment by spacekitteh** [comment]
Any update on this?

**Comment by attractedtofire** [comment]
Hello and first of all thanks for the great work and product!
I've been playing around with the rather outdated self-hosted Zotero data-server mentioned above and was wondering if there are any news on a possible up-to-date docker setup.  (I know it is not of any particular priority to you guys but since I'd have an interesting use case I was wondering if its worth waiting a bit longer or if there is no use in doing so).
Thanks again

**Comment by th0ma5w** [comment]
Any update on this? Having to share research with a third party, regardless of assurances, is a show stopper for my organization and I'm sure others.

**Comment by dstillman** [comment]
If you're at an organization that might be interested in a private dataserver with official support, email us at support@zotero.org to discuss further.

**Comment by spacekitteh** [comment]
Couldn't a very simple README have been created with the same effort you used to write your initial response, @dstillman? I appreciate that it's completely unsupported, but even just a single paragraph would be helpful.

**Comment by ThibaultSauzedde** [comment]
Does there is news for a private dataserver with official support for organizations?

**Comment by abdalazizrashid** [comment]
Any news regarding this?
